name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  token: ${{ secrets.PAT }}
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Run
              run: |
                  npm ci
                  npm run build
            - name: Bump version
              if: github.event_name != 'pull_request'
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  npm version patch -m "[no ci] Bump version to %s"
                  git push --follow-tags
